apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: huly
  annotations:
    cloud.google.com/load-balancer-type: "external"
    networking.gke.io/load-balancer-ipv4: "huly-static-ip"
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
