name: Deploy Huly to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Step 3: Authenticate with GKE
    - name: Authenticate with GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone ${{ secrets.GCP_ZONE }}

    # Step 4: Create Namespace (if necessary)
    - name: Create Namespace
      run: |
        kubectl create namespace huly || true

    # Step 5: Apply Configurations (ConfigMaps and Secrets)
    - name: Apply Configurations
      run: |
        kubectl apply -f kube/config/ -n huly

    # Step 6: Apply Persistent Volume Claims
    - name: Apply Persistent Volume Claims
      run: |
        kubectl apply -f elastic/elastic-persistentvolumeclaim.yaml -n huly
        kubectl apply -f minio/files-persistentvolumeclaim.yaml -n huly
        kubectl apply -f mongodb/mongodb-persistentvolumeclaim.yml -n huly

    # Step 7: Deploy Application Services
    - name: Deploy Application
      run: |
        kubectl apply -f kube/ -n huly

    # Step 8: Verify Deployment
    - name: Verify Deployment
      run: |
        kubectl get all -n huly
